# Generated by Django 6.0.3 on 2026-03-14 10:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidades', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo_mejoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('precio_puntos', models.IntegerField()),
                ('url_recurso', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'catalogo_mejoras',
            },
        ),
        migrations.CreateModel(
            name='Mejoras_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_equipada', models.BooleanField(default=False)),
                ('fecha_adquisicion', models.DateTimeField(auto_now_add=True)),
                ('mejora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mejoras.catalogo_mejoras')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'mejoras_usuario',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(default=0, help_text='Las estrellas no pueden ser más de 5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('receptor_comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos_comunidad', to='comunidades.comunidad')),
                ('receptor_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos_perfil', to='usuarios.usuario')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_emitidos', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'votos',
            },
        ),
    ]
