# Generated by Django 6.0.3 on 2026-04-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mejoras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo_mejoras',
            name='url_recurso',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='tienda/'),
        ),
    ]
