# Generated by Django 6.0.3 on 2026-04-11 16:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0008_comunidad_tienda_habilitada'),
        ('mejoras', '0002_alter_catalogo_mejoras_url_recurso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_mejoras',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_tienda', to='comunidades.comunidad'),
        ),
        migrations.AddField(
            model_name='catalogo_mejoras',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mejoras_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogo_mejoras',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PeticionMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('url_recurso', models.ImageField(max_length=500, upload_to='peticiones_tienda/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('precio_sugerido', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peticiones_recibidas', to='comunidades.comunidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peticiones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'peticiones_mejora',
            },
        ),
    ]
