# Generated by Django 6.0.3 on 2026-04-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mejoras', '0003_catalogo_mejoras_comunidad_catalogo_mejoras_creador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_mejoras',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
    ]
