# Generated by Django 6.0.3 on 2026-04-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mejoras', '0004_catalogo_mejoras_esta_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo_mejoras',
            name='nombre',
        ),
    ]
