# Generated by Django 6.0.3 on 2026-04-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mejoras', '0005_remove_catalogo_mejoras_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peticionmejora',
            name='nombre',
        ),
    ]
