# Generated by Django 6.0.3 on 2026-04-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mejoras', '0006_remove_peticionmejora_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_mejoras',
            name='datos_extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
