# Generated by Django 6.0.3 on 2026-05-02 17:38

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0010_miembroscomunidad_delete_miembros_comunidades'),
        ('mejoras', '0007_catalogo_mejoras_datos_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalogo_mejoras',
            new_name='CatalogoMejoras',
        ),
        migrations.RenameModel(
            old_name='Mejoras_usuario',
            new_name='MejoraUsuario',
        ),
        migrations.AlterField(
            model_name='voto',
            name='estrellas',
            field=models.IntegerField(default=0, help_text='Las estrellas no pueden ser más de 5.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
