# Generated by Django 6.0.3 on 2026-03-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('SOLICITUD', 'Solicitud'), ('DENEGADO', 'Denegado')], default='SOLICITUD', max_length=20),
        ),
    ]
