# Generated by Django 6.0.3 on 2026-03-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_is_active_usuario_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='es_publico',
            field=models.BooleanField(default=True),
        ),
    ]
