# Generated by Django 6.0.3 on 2026-04-05 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_reporte'),
        ('usuarios', '0005_perfil_es_publico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='url_avatar',
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.imagengaleria'),
        ),
    ]
