# Generated by Django 6.0.3 on 2026-04-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0008_alter_imagenes_galeria_url_s3'),
        ('usuarios', '0006_remove_perfil_url_avatar_perfil_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fondo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fondo', to='contenido.imagengaleria'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='marco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marco', to='contenido.imagengaleria'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='contenido.imagengaleria'),
        ),
    ]
