# Generated by Django 6.0.3 on 2026-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfil_fondo_perfil_marco_alter_perfil_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='imagen',
        ),
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fondo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='marco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
