# Generated by Django 6.0.3 on 2026-04-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_perfil_imagen_perfil_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estilo_post',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
