# Generated by Django 6.0.3 on 2026-04-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_perfil_estilo_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
