# Generated by Django 6.0.3 on 2026-04-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_perfil_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='esta_online',
            field=models.BooleanField(default=False),
        ),
    ]
