# Generated by Django 6.0.3 on 2026-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_perfil_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('DESCONECTADO', 'Desconectado'), ('OCUPADO', 'Ocupado')], default='DESCONECTADO', max_length=20),
        ),
    ]
