# Generated by Django 6.0.3 on 2026-04-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_perfil_esta_online'),
        ('usuarios', '0011_perfil_estado'),
    ]

    operations = [
    ]
