# Generated by Django 6.0.3 on 2026-05-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_merge_0011_perfil_esta_online_0011_perfil_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fondo_perfil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
