# Generated by Django 6.0.3 on 2026-05-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_perfil_fondo_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='orden_comunidades',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
