# Generated by Django 6.0.3 on 2026-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_perfil_orden_comunidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='color_tema',
            field=models.CharField(default='#C35E34', max_length=7),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fuente_perfil',
            field=models.CharField(default='Outfit', max_length=50),
        ),
    ]
