# Generated by Django 6.0.3 on 2026-04-25 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0008_comunidad_tienda_habilitada'),
        ('mensajeria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salas_chat',
            name='es_publica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salas_chat',
            name='invite_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salas_chat',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='salas_pertenecientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salas_chat',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad'),
        ),
    ]
