# Generated by Django 6.0.3 on 2026-04-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_salas_chat_es_publica_salas_chat_invite_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes_chat',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
