# Generated by Django 6.0.3 on 2026-04-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_mensajes_chat_leido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes_chat',
            old_name='leido',
            new_name='es_leido',
        ),
        migrations.AddField(
            model_name='mensajes_chat',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
