# Generated by Django 6.0.3 on 2026-05-02 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0010_miembroscomunidad_delete_miembros_comunidades'),
        ('mensajeria', '0004_rename_leido_mensajes_chat_es_leido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaChatMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'salas_chat_miembros',
                'managed': False,
            },
        ),
        migrations.RenameModel(
            old_name='Mensajes_chat',
            new_name='MensajeChat',
        ),
        migrations.RenameModel(
            old_name='Participantes_chat',
            new_name='ParticipanteChat',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameModel(
                    old_name='Salas_chat',
                    new_name='SalaChat',
                ),
                migrations.RemoveField(
                    model_name='salachat',
                    name='miembros',
                ),
                migrations.AddField(
                    model_name='salachat',
                    name='miembros',
                    field=models.ManyToManyField(blank=True, related_name='salas_pertenecientes', through='mensajeria.SalaChatMiembro', to=settings.AUTH_USER_MODEL),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='mensajechat',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajeria.salachat'),
        ),
        migrations.AlterField(
            model_name='participantechat',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajeria.salachat'),
        ),
    ]
