# Generated by Django 6.0.3 on 2026-05-03 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0005_salachatmiembro_rename_mensajes_chat_mensajechat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajechat',
            name='es_leido',
        ),
        migrations.RemoveField(
            model_name='mensajechat',
            name='fecha_lectura',
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='borrado_para',
            field=models.ManyToManyField(blank=True, related_name='mensajes_borrados_localmente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='borrado_para_todos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='es_editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='leido_por',
            field=models.ManyToManyField(blank=True, related_name='mensajes_leidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='referencia_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='mensajeria.mensajechat'),
        ),
    ]
