# Generated by Django 6.0.3 on 2026-05-03 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0006_remove_mensajechat_es_leido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajechat',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEN', 'Imagen'), ('VIDEO', 'Vídeo'), ('SISTEMA', 'Sistema')], default='TEXTO', max_length=20),
        ),
        migrations.AddField(
            model_name='participantechat',
            name='apodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salachat',
            name='avatar_s3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='salachat',
            name='configuracion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PersonalizacionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_fondo', models.CharField(blank=True, max_length=50, null=True)),
                ('color_burbuja_mio', models.CharField(blank=True, max_length=50, null=True)),
                ('color_burbuja_otro', models.CharField(blank=True, max_length=50, null=True)),
                ('color_texto_mio', models.CharField(blank=True, max_length=50, null=True)),
                ('color_texto_otro', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen_fondo_s3', models.CharField(blank=True, max_length=500, null=True)),
                ('forma_burbuja', models.CharField(default='redondeada', max_length=50)),
                ('font_size', models.IntegerField(default=14)),
                ('tema', models.CharField(default='claro', max_length=20)),
                ('sala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalizacion_v2', to='mensajeria.salachat')),
            ],
            options={
                'db_table': 'chat_personalizacion',
            },
        ),
        migrations.CreateModel(
            name='ApodoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodo', models.CharField(max_length=100)),
                ('asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apodos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('asignador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apodos_dados', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apodos_personalizados', to='mensajeria.salachat')),
            ],
            options={
                'db_table': 'chat_apodos',
                'unique_together': {('sala', 'asignador', 'asignado')},
            },
        ),
    ]
