# Generated by Django 6.0.3 on 2026-05-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0007_mensajechat_tipo_participantechat_apodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salachat',
            name='es_general',
            field=models.BooleanField(default=False),
        ),
    ]
