# Generated by Django 6.0.3 on 2026-05-04 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0008_salachat_es_general'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaChatMiembro',
        ),
        migrations.AlterField(
            model_name='salachat',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='salas_pertenecientes', through='mensajeria.ParticipanteChat', to=settings.AUTH_USER_MODEL),
        ),
    ]
