# Generated by Django 6.0.3 on 2026-05-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0009_delete_salachatmiembro_alter_salachat_miembros'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacionchat',
            name='color_nombre_mio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personalizacionchat',
            name='color_nombre_otro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personalizacionchat',
            name='estilo_burbuja',
            field=models.CharField(default='estandar', max_length=50),
        ),
        migrations.AddField(
            model_name='personalizacionchat',
            name='gradiente_fondo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personalizacionchat',
            name='patron_fondo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
