# Generated by Django 6.0.3 on 2026-05-05 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0010_personalizacionchat_color_nombre_mio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizacionchat',
            name='estilo_burbuja',
            field=models.CharField(default='solido', max_length=50),
        ),
        migrations.CreateModel(
            name='LecturaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajeria.mensajechat')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_lecturas_mensajes',
                'unique_together': {('mensaje', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='leido_por',
            field=models.ManyToManyField(blank=True, related_name='mensajes_leidos', through='mensajeria.LecturaMensaje', to=settings.AUTH_USER_MODEL),
        ),
    ]
