# Generated by Django 6.0.3 on 2026-05-06 18:11

import mensajeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0011_alter_personalizacionchat_estilo_burbuja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajechat',
            name='url_archivo_s3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=mensajeria.models.chat_image_path),
        ),
    ]
