# Generated by Django 6.0.3 on 2026-05-06 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0017_comentario_padre'),
        ('mensajeria', '0012_alter_mensajechat_url_archivo_s3'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajechat',
            name='imagen_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_como_principal', to='contenido.imagengaleria'),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='imagenes',
            field=models.ManyToManyField(blank=True, related_name='mensajes_donde_aparece', to='contenido.imagengaleria'),
        ),
    ]
