# Generated by Django 6.0.3 on 2026-03-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_portada', models.CharField(blank=True, max_length=500, null=True)),
                ('es_publica', models.BooleanField(default=True)),
                ('es_verificada', models.BooleanField(default=False)),
                ('rating_actual', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comunidades',
            },
        ),
        migrations.CreateModel(
            name='Miembros_comunidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(default='Miembro', max_length=20)),
                ('estado_peticion', models.CharField(default='ACEPTADO', max_length=20)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'miembros_comunidades',
            },
        ),
    ]
