# Generated by Django 6.0.3 on 2026-03-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='miembros_comunidades',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad'),
        ),
        migrations.AddField(
            model_name='miembros_comunidades',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
