# Generated by Django 6.0.3 on 2026-03-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0003_alter_comunidad_url_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembros_comunidades',
            name='estado_peticion',
        ),
    ]
