# Generated by Django 6.0.3 on 2026-04-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0004_remove_miembros_comunidades_estado_peticion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='min_rating_acceso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
