# Generated by Django 6.0.3 on 2026-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0005_comunidad_min_rating_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='color_tema',
            field=models.CharField(default='#C35E34', max_length=7),
        ),
    ]
