# Generated by Django 6.0.3 on 2026-04-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0006_comunidad_color_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros_comunidades',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Moderador', 'Moderador'), ('Miembro', 'Miembro')], default='Miembro', max_length=20),
        ),
    ]
