# Generated by Django 6.0.3 on 2026-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0007_alter_miembros_comunidades_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='tienda_habilitada',
            field=models.BooleanField(default=False),
        ),
    ]
