# Generated by Django 6.0.3 on 2026-05-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0008_comunidad_tienda_habilitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='fondo_posts_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='fuente_comunidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='url_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='comunidades/avatares/'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='url_fondo',
            field=models.ImageField(blank=True, null=True, upload_to='comunidades/fondos/'),
        ),
    ]
