# Generated by Django 6.0.3 on 2026-05-02 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0009_comunidad_fondo_posts_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Miembros_comunidades',
            new_name='MiembrosComunidad',
        ),
        migrations.AlterField(
            model_name='miembroscomunidad',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_comunidades', to='comunidades.comunidad'),
        ),
    ]
