# Generated by Django 6.0.3 on 2026-05-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0010_miembroscomunidad_delete_miembros_comunidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tags de Comunidades',
                'db_table': 'tags_comunidades',
            },
        ),
        migrations.AddField(
            model_name='comunidad',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='comunidades', to='comunidades.tagcomunidad'),
        ),
    ]
