# Generated by Django 6.0.3 on 2026-05-03 16:51
#
# NOTA: Esta migración es un duplicado de 0011_tags_comunidades.py
# que se generó en la misma sesión de desarrollo. Sus operaciones han sido
# vaciadas para evitar el error "table already exists" en bases de datos
# limpias (CI/SQLite). Toda la DDL real reside en 0011_tags_comunidades.py.
# Esta migración se conserva únicamente como nodo de dependencia para
# la migración de merge 0012.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0010_miembroscomunidad_delete_miembros_comunidades'),
    ]

    operations = []
