# Generated by Django 6.0.3 on 2026-05-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0011_tagcomunidad_comunidad_tags'),
        ('comunidades', '0011_tags_comunidades'),
    ]

    operations = [
    ]
