# Generated by Django 6.0.3 on 2026-05-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0012_merge_20260503_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='url_marco',
            field=models.ImageField(blank=True, null=True, upload_to='comunidades/marcos/'),
        ),
    ]
