# Generated by Django 6.0.3 on 2026-03-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes_galeria',
            name='url_s3',
            field=models.ImageField(max_length=500, upload_to='galeria/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='url_archivo_s3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='publicaciones/archivos/'),
        ),
    ]
