# Generated by Django 6.0.3 on 2026-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_alter_imagenes_galeria_url_s3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes_galeria',
            name='es_publica',
        ),
        migrations.AddField(
            model_name='imagenes_galeria',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
