# Generated by Django 6.0.3 on 2026-04-02 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0004_remove_miembros_comunidades_estado_peticion'),
        ('contenido', '0003_remove_imagenes_galeria_es_publica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes_galeria',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad'),
        ),
    ]
