# Generated by Django 6.0.3 on 2026-04-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_alter_imagenes_galeria_comunidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='url_archivo_s3',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagengaleria'),
        ),
        migrations.AlterField(
            model_name='imagenes_galeria',
            name='url_s3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='publicaciones/archivos'),
        ),
    ]
