# Generated by Django 6.0.3 on 2026-04-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0005_comunidad_min_rating_acceso'),
        ('contenido', '0005_remove_publicacion_url_archivo_s3_publicacion_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad'),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='Imagenes_galeria',
            name='es_publica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='Imagenes_galeria',
            name='tipo_archivo',
            field=models.CharField(choices=[('I', 'Imagen'), ('V', 'Video')], default='I', max_length=1),
        ),
        migrations.DeleteModel(
            name='Imagenes_en_colecciones',
        ),
    ]
