# Generated by Django 6.0.3 on 2026-04-04 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0005_comunidad_min_rating_acceso'),
        ('contenido', '0006_coleccion_comunidad_coleccion_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_objeto', models.CharField(choices=[('POST', 'Publicación'), ('IMAGEN', 'Imagen'), ('COMUNIDAD', 'Comunidad'), ('COMENTARIO', 'Comentario')], max_length=20)),
                ('objeto_id', models.IntegerField()),
                ('motivo', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTO', 'Resuelto'), ('DESESTIMADO', 'Desestimado')], default='PENDIENTE', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad')),
                ('informador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reportes',
            },
        ),
    ]
