# Generated by Django 6.0.3 on 2026-04-06 09:34

import contenido.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes_galeria',
            name='url_s3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=contenido.models._definir_ruta_almacenamiento),
        ),
    ]
