# Generated by Django 6.0.3 on 2026-04-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0008_alter_imagenes_galeria_url_s3'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagenes',
            field=models.ManyToManyField(blank=True, related_name='publicaciones_asociadas', to='imagengaleria'),
        ),
    ]
