# Generated by Django 6.0.3 on 2026-04-12 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_publicacion_imagenes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardado_por', to='contenido.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_guardados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts_guardados',
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
    ]
