# Generated by Django 6.0.3 on 2026-05-02 17:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0010_miembroscomunidad_delete_miembros_comunidades'),
        ('contenido', '0010_postguardado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imagenes_galeria',
            new_name='ImagenGaleria',
        ),
        migrations.RenameModel(
            old_name='Me_gustas',
            new_name='MeGusta',
        ),
    ]
