# Generated by Django 6.0.3 on 2026-05-03 10:33

import contenido.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0011_rename_imagenes_galeria_imagengaleria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagengaleria',
            name='url_s3',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=contenido.models._definir_ruta_almacenamiento),
        ),
    ]
