# Generated by Django 6.0.3 on 2026-05-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0012_alter_imagengaleria_url_s3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='imagenes',
        ),
    ]
