# Generated by Django 6.0.3 on 2026-05-03 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0013_remove_publicacion_imagenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.imagengaleria')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.publicacion')),
            ],
            options={
                'db_table': 'publicacion_imagenes',
                'ordering': ['orden'],
                'unique_together': {('publicacion', 'imagen')},
            },
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagenes',
            field=models.ManyToManyField(blank=True, related_name='publicaciones_asociadas', through='contenido.PublicacionImagen', to='contenido.imagengaleria'),
        ),
    ]
