# Generated by Django 6.0.3 on 2026-05-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0014_publicacionimagen_publicacion_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagenes',
            field=models.ManyToManyField(blank=True, related_name='publicaciones_asociadas', through='contenido.PublicacionImagen', through_fields=('publicacion', 'imagen'), to='contenido.imagengaleria'),
        ),
    ]
