# Generated by Django 6.0.3 on 2026-05-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0015_alter_publicacion_imagenes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacionimagen',
            old_name='imagen',
            new_name='imagengaleria',
        ),
        migrations.AlterUniqueTogether(
            name='publicacionimagen',
            unique_together={('publicacion', 'imagengaleria')},
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagenes',
            field=models.ManyToManyField(blank=True, related_name='publicaciones_asociadas', through='contenido.PublicacionImagen', through_fields=('publicacion', 'imagengaleria'), to='contenido.imagengaleria'),
        ),
    ]
