# Generated by Django 6.0.3 on 2026-05-04 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0016_rename_imagen_publicacionimagen_imagengaleria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='contenido.comentario'),
        ),
    ]
