# Generated by Django 6.0.3 on 2026-05-11 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0017_comentario_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='imagenes',
            field=models.ManyToManyField(related_name='en_colecciones', to='contenido.imagengaleria'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenido.imagengaleria'),
        ),
    ]
