# Generated by Django 6.0.3 on 2026-03-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidades', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_notoficacion', models.DateTimeField(auto_now_add=True)),
                ('referencia_comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad')),
                ('referencia_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_generadas', to='usuarios.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
    ]
