# Generated by Django 6.0.3 on 2026-03-17 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0003_alter_comunidad_url_portada'),
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha_notoficacion',
            new_name='fecha_notificacion',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='referencia_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='referencia_comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='referencia_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_generadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
